name: Quest
version: '${project.version}'
main: es.outlook.adriansr.quest.main.QuestPlugin
api-version: 1.18
authors: [ AdrianSR ]
description: Quest plugin
commands:
  quest:
    usage: '/quest <player> <quest>'
    description: 'start a quest'
libraries:
  - 'org.mongodb:mongodb-driver-sync:4.2.1'